server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://homelab:8888"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
