server:
  port: 8083

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:mongo}:27017/notification_db
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mail:
      enabled: false
